"""Add position to executive model

Revision ID: 2746976304a4
Revises: 9b51aece7be2
Create Date: 2024-01-16 11:50:47.935850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2746976304a4'
down_revision = '9b51aece7be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
