"""add cover photo attribute to Article model

Revision ID: 4be93fd1f31f
Revises: e451ebd4cce4
Create Date: 2024-04-04 07:27:23.471620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be93fd1f31f'
down_revision = 'e451ebd4cce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('cover_photo')

    # ### end Alembic commands ###
