"""empty message

Revision ID: 8bdecea1ac8a
Revises: b5772a35c3a9
Create Date: 2024-05-15 12:46:33.626747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdecea1ac8a'
down_revision = 'b5772a35c3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
