"""Add Article category model

Revision ID: cccbc8bd6d72
Revises: e311a03dea98
Create Date: 2024-04-15 11:45:38.168770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccbc8bd6d72'
down_revision = 'e311a03dea98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('article_category_id', 'article_category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('article_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
