"""Add department column to Executive Model

Revision ID: e311a03dea98
Revises: 4be93fd1f31f
Create Date: 2024-04-12 12:38:28.560445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e311a03dea98'
down_revision = '4be93fd1f31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###
